"""Constants for the Quby ToonAPI."""

ACTIVE_STATE_AWAY = 3
ACTIVE_STATE_COMFORT = 0
ACTIVE_STATE_HOLIDAY = 4
ACTIVE_STATE_HOME = 1
ACTIVE_STATE_NONE = -1
ACTIVE_STATE_OFF = -1
ACTIVE_STATE_SLEEP = 2

BURNER_STATE_OFF = 0
BURNER_STATE_ON = 1
BURNER_STATE_PREHEATING = 3
BURNER_STATE_TAP_WATER = 2

HEATING_TYPE_GAS = 1

PROGRAM_STATE_OFF = 0
PROGRAM_STATE_ON = 1
PROGRAM_STATE_OVERRIDE = 2

TOON_API_BASE_PATH = "/"
TOON_API_HOST = "api.toon.eu"
TOON_API_PORT = 443
TOON_API_SCHEME = "https"
TOON_API_VERSION = "v3"
