---
name: Continuous Integration

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code from GitHub
        uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements_test.txt
          pip install -r requirements.txt
          pip install pre-commit
          pip list
          pre-commit --version
      - name: Run pre-commit on all files
        run: |
          pre-commit run --all-files --show-diff-on-failure
